PRONAME:= dstl
VERSION:=1.0.0
TARGET:= lib$(PRONAME)
PRE_DEFINED := 
BUILD_PATH := $(shell pwd)
INCLUDES := $(BUILD_PATH)/inc
LIBS_PATH := \
            ../lib
LIBS := darithmetic dcomponent dvector

include ../../shared.mk
