MODULE:=duye_file_server_test

VERSION:=

TARGET:=$(MODULE)

PRE_DEFINED:= 

BUILD_PATH:=$(shell pwd)

SUBDIRS:=

INCLUDES:= \
	$(INC_DIR)/duyebase \
	$(INC_DIR)/duyenets

SRCDIRS:=$(BUILD_PATH)

LIBS_PATH:=$(LIB_DIR)

LIBS:=duyebase duyenets

SLIBS:=

OUT_HEADS:=

include $(ROOT_DIR)/app.mk
