PRONAME:=dnetwork
VERSION := $(shell cat VERSION|awk '{print $$2}'|cut -c 2-)
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=$(BUILD_PATH)/inc \

LIBS_PATH:= 

LIBS:= 

include ../shared.mk
