MODULE:=duye_file_server_test

VERSION:=

TARGET:=$(MODULE)

PRE_DEFINED:= 

BUILD_PATH:=$(shell pwd)

SUBDIRS:=

INCLUDES:= \
 	$(INC_DIR) \
	$(INS_INC_DIR)/duyezero \

SRCDIRS:=$(BUILD_PATH)

LIBS_PATH:=$(LIB_DIR) $(INS_LIB_DIR)

LIBS:=duyezero duyeone

SLIBS:=

OUT_HEADS:=

include $(ROOT_DIR)/app.mk
