MODULE:=duye_logger_test

VERSION:=

TARGET:=$(MODULE)

PRE_DEFINED:= 

BUILD_PATH:=$(shell pwd)

SUBDIRS:=

INCLUDES:=$(INC_DIR)

SRCDIRS:=$(BUILD_PATH)

LIBS_PATH:=$(LIB_DIR)

LIBS:=duyezero

SLIBS:=

OUT_HEADS:=

include $(ROOT_DIR)/app.mk
