all:
	cd duyebase; make; cd -
	cd duyeone; make; cd -
	cd duyetwo; make; cd -
	cd duyefour; make; cd -
	@echo '===== lib code total lines '`find -name \*.[c,h]* | xargs cat | wc -l` '====='

clean:
	cd duyebase; make clean; cd -
	cd duyeone; make clean; cd -
	cd duyetwo; make clean; cd -
	cd duyefour; make clean; cd -

cleanall:
	cd duyebase; make cleanall; cd -
	cd duyeone; make cleanall; cd -
	cd duyetwo; make cleanall; cd -
	cd duyefour; make cleanall; cd -

install:
	cd duyebase; make install; cd -
	cd duyeone; make install; cd -
	cd duyetwo; make install; cd -
	cd duyefour; make install; cd -

uninstall:
	cd duyebase; make uninstall; cd -
	cd duyeone; make uninstall; cd -
	cd duyetwo; make uninstall; cd -
	cd duyefour; make uninstall; cd -
