PRONAME:= dposix
TARGET:= lib$(PRONAME)
PRE_DEFINED := 
BUILD_PATH := $(shell pwd)

INCLUDES := ../ips/inc \
			../stdio/inc \
            ../thread/inc \

LIBS_PATH := ../lib \

LIBS := dipc dstdio dthread

include ../../shared.mk
